/*
 HMP v1.1.1 for oracle
*/


CREATE SEQUENCE seq_conditional_spec_mst_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_model_param_spec_mst_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_eqp_spec_link_mst_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_param_spec_mst_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_param_dimension_trx_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

ALTER TABLE EQP_MST_PDM ADD MODEL_NAME VARCHAR2(32);

ALTER TABLE EQP_EVENT_MST_PDM ADD TIMEOUT NUMBER(38);

ALTER TABLE TRACE_TRX_PDM ADD (message_group varchar2(1024));
ALTER TABLE PARAM_FEATURE_TRX_PDM ADD (message_group varchar2(1024));
ALTER TABLE PARAM_HEALTH_TRX_PDM ADD (message_group varchar2(1024));


ALTER TABLE ALARM_TRX_PDM ADD (RULE_NAME VARCHAR2(32));
ALTER TABLE ALARM_TRX_PDM ADD (CONDITION VARCHAR2(4000));

ALTER TABLE TRACE_TRX_PDM ADD (RULE_NAME VARCHAR2(32));
ALTER TABLE TRACE_TRX_PDM ADD (CONDITION VARCHAR2(4000));

ALTER TABLE PARAM_MST_PDM ADD (DATA_TYPE VARCHAR2(32));
ALTER TABLE PARAM_MST_PDM MODIFY(DATA_TYPE VARCHAR2(32) DEFAULT 'CONTINUOUS' );

-- -----------------------------------------------------
-- Table CONDITIONAL_SPEC_MST_PDM
-- -----------------------------------------------------
CREATE TABLE CONDITIONAL_SPEC_MST_PDM (
  RAWID             NUMBER(38) NOT NULL,
  MODEL_NAME        VARCHAR2(32) NOT NULL,
  RULE_NAME         VARCHAR2(32) NOT NULL,
  EXPRESSION        VARCHAR2(4000),
  EXPRESSION_VALUE  VARCHAR2(4000),
  CONDITION         VARCHAR2(4000),
  DESCRIPTION       VARCHAR2(2048) NULL,
  CREATE_BY         VARCHAR2(32) NULL,
  CREATE_DTTS       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_BY         VARCHAR2(32) NULL,
  UPDATE_DTTS       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_CONDITIONAL_SPEC_MST_PDM ON CONDITIONAL_SPEC_MST_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_CONDITIONAL_SPEC_MST_PDM ON CONDITIONAL_SPEC_MST_PDM (MODEL_NAME, RULE_NAME) TABLESPACE NPDM_IDX;


-- -----------------------------------------------------
-- Table MODEL_PARAM_SPEC_MST_PDM
-- -----------------------------------------------------
CREATE TABLE MODEL_PARAM_SPEC_MST_PDM (
  RAWID                         NUMBER(38) NOT NULL,
  CONDITIONAL_SPEC_MST_RAWID    NUMBER(38) NOT NULL,
  PARAM_NAME                    VARCHAR2(256) NOT NULL,
  UPPER_ALARM_SPEC              FLOAT,
  UPPER_WARNING_SPEC            FLOAT,
  TARGET                        FLOAT,
  LOWER_ALARM_SPEC              FLOAT,
  LOWER_WARNING_SPEC            FLOAT,
  DESCRIPTION                   VARCHAR2(2048) NULL,
  CREATE_BY                     VARCHAR2(32) NULL,
  CREATE_DTTS                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_BY                     VARCHAR2(32) NULL,
  UPDATE_DTTS                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_MODEL_PARAM_SPEC_MST_PDM ON MODEL_PARAM_SPEC_MST_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_MODEL_PARAM_SPEC_MST_PDM ON MODEL_PARAM_SPEC_MST_PDM (CONDITIONAL_SPEC_MST_RAWID, PARAM_NAME) TABLESPACE NPDM_IDX;


-- -----------------------------------------------------
-- Table EQP_SPEC_LINK_MST_PDM
-- -----------------------------------------------------
CREATE TABLE EQP_SPEC_LINK_MST_PDM (
  RAWID                         NUMBER(38) NOT NULL,
  EQP_MST_RAWID                 NUMBER(38) NOT NULL,
  CONDITIONAL_SPEC_MST_RAWID    NUMBER(38) NOT NULL,
  ORDERING                      NUMBER(5) DEFAULT 1,
  DESCRIPTION                   VARCHAR2(2048) NULL,
  CREATE_BY                     VARCHAR2(32) NULL,
  CREATE_DTTS                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_BY                     VARCHAR2(32) NULL,
  UPDATE_DTTS                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_EQP_SPEC_LINK_MST_PDM ON EQP_SPEC_LINK_MST_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_EQP_SPEC_LINK_MST_PDM ON EQP_SPEC_LINK_MST_PDM (EQP_MST_RAWID, CONDITIONAL_SPEC_MST_RAWID) TABLESPACE NPDM_IDX;


-- -----------------------------------------------------
-- Table PARAM_SPEC_MST_PDM
-- -----------------------------------------------------
CREATE TABLE PARAM_SPEC_MST_PDM (
  RAWID                             NUMBER(38) NOT NULL,
  PARAM_MST_RAWID                   NUMBER(38) NOT NULL,
  EQP_SPEC_LINK_MST_RAWID           NUMBER(38) NOT NULL,
  UPPER_ALARM_SPEC                  FLOAT,
  UPPER_WARNING_SPEC                FLOAT,
  TARGET                            FLOAT,
  LOWER_ALARM_SPEC                  FLOAT,
  LOWER_WARNING_SPEC                FLOAT,
  DESCRIPTION                       VARCHAR2(2048) NULL,
  CREATE_BY                         VARCHAR2(32) NULL,
  CREATE_DTTS                       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_BY                         VARCHAR2(32) NULL,
  UPDATE_DTTS                       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_PARAM_SPEC_MST_PDM ON PARAM_SPEC_MST_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_PARAM_SPEC_MST_PDM ON PARAM_SPEC_MST_PDM (PARAM_MST_RAWID, EQP_SPEC_LINK_MST_RAWID) TABLESPACE NPDM_IDX;


CREATE TABLE PARAM_DIMENSION_TRX_PDM
(
    RAWID           NUMBER(38)          NOT NULL,
    PARAM_MST_RAWID NUMBER(38)          NOT NULL,
    BEGIN_DTTS      TIMESTAMP (6)       NOT NULL,
    END_DTTS        TIMESTAMP (6)       NOT NULL,
    VALUE           VARCHAR2(1024),
    MESSAGE_GROUP   VARCHAR2(1024)
) TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_PARAM_DIMENSION_TRX_PDM ON PARAM_DIMENSION_TRX_PDM (RAWID) TABLESPACE NPDM_IDX;