
export const ActionTypeConstant = {

    ////////////////////////////////////////
    // Sample
    COUNTER_INCREMENT: 'COUNTER_INCREMENT',
    COUNTER_DECREMENT: 'COUNTER_DECREMENT',

    ////////////////////////////////////////
    // current to dashboard, workspace when routing
    DASHBOARD: 'DASHBOARD',
    WORKSPACE: 'WORKSPACE',
    WORKSPACE_TASKER: 'WORKSPACE_TASKER',

    APPCONFIG: 'APPCONFIG',
    USERCONFIG: 'USERCONFIG',
    GLOBALCONFIG: 'GLOBALCONFIG',

    SIGNED_USER: 'SIGNED_USER',
	LOGOUT_USER: 'LOGOUT_USER',

    CHECK_PAGE: 'CHECK_PAGE',

    ////////////////////////////////////////
    // DASHBOARD
    SET_DASHBOARDS: 'SET_DASHBOARDS',
    ADD_DASHBOARD: 'ADD_DASHBOARD',
    UPDATE_DASHBOARD: 'UPDATE_DASHBOARD',
    UPDATE_DASHBOARD_ORDER: 'UPDATE_DASHBOARD_ORDER',
    REMOVE_DASHBOARD: 'REMOVE_DASHBOARD',
    CLEAR_DASHBOARDS: 'CLEAR_DASHBOARDS',
    SET_HOME_DASHBOARD: 'SET_HOME_DASHBOARD',
    SET_CURRENT_PAGE_IN_DASHBOARD: 'SET_CURRENT_PAGE_IN_DASHBOARD',
    MOVE_WIDGET_IN_DASHBOARD: 'MOVE_WIDGET_IN_DASHBOARD',

    ////////////////////////////////////////
    // WIDGET
    ADD_WIDGET: 'ADD_WIDGET',
    ADDING_WIDGET: 'ADDING_WIDGET',
    REMOVE_WIDGET: 'REMOVE_WIDGET',
    UPDATE_WIDGET: 'UPDATE_WIDGET',
    UPDATE_WIDGET_SIZE: 'UPDATE_WIDGET_SIZE',
    UPDATE_WIDGET_TITLE: 'UPDATE_WIDGETi_TITLE',

    SELECT_WIDGET_CHART_ITEM: 'SELECT_WIDGET_CHART_ITEM',
    UNSELECT_WIDGET_CHART_ITEM: 'UNSELECT_WIDGET_CHART_ITEM',
    CLEAR_WIDGET_CHART_ALL_ITEMS: 'CLEAR_WIDGET_CHART_ALL_ITEMS',

    ////////////////////////////////////////
    // WORKSPACE
    SET_WORKSPACES: 'SET_WORKSPACES',
    ADD_WORKSPACE: 'ADD_WORKSPACE',
    REMOVE_WORKSPACE: 'REMOVE_WORKSPACE',
    CLEAR_WORKSPACES: 'REMOVE_WORKSPACES',

    ////////////////////////////////////////
    // TASKER
    SET_TASKER: 'SET_TASKER',
    SET_TASKERS: 'SET_TASKERS',
    ADD_TASKER: 'ADD_TASKER',
    REMOVE_TASKER: 'REMOVE_TASKER',
    UPDATE_TASKER: 'UPDATE_TASKER',

    SELECT_TASKER_CHART_ITEM: 'SELECT_TASKER_CHART_ITEM',
    UNSELECT_TASKER_CHART_ITEM: 'UNSELECT_TASKER_CHART_ITEM',
    CLEAR_TASKER_CHART_ALL_ITEMS: 'CLEAR_TASKER_CHART_ALL_ITEMS',

    ////////////////////////////////////////
    // GMB Sidebar
    // open close
    OPEN_SIDE_BAR_SMALL: 'OPEN_SIDE_BAR_SMALL',
    OPEN_SIDE_BAR_FULL: 'OPEN_SIDE_BAR_FUL',
    CLOSE_SIDE_BAR: 'CLOSE_SIDE_BAR',

    OPEN_FILTER_CONTAINER: 'open',
	CLOSE_FILTER_CONTAINER: 'hide',

    // GMB Type Id
    // must set directive name
    GNB_APP_LIST: 'a3pTaskerList',
    GNB_WIDGET_LIST: 'a3pWidgetList',
    GNB_NOTICE_LIST: 'a3pNoticeList',
    GNB_DASHBOARD_LIST: 'a3pDashboardList',
    GNB_ACUBED_MAP: 'a3pAcubedmap',
    GNB_ACUBED_NET: 'a3pAcubednet',
    GNB_APP_CONFIG: 'a3pAppconfig',

    // widget configuration
    OPEN_WIDGET_PROPERTIES: 'OPEN_WIDGET_PROPERTIES',
    CLOSE_WIDGET_PROPERTIES: 'CLOSE_WIDGET_PROPERTIES',
    APPLY_WIDGET_PROPERTIES: 'APPLY_WIDGET_PROPERTIES',

    // in ther future
    OPEN_TASKER_PROPERTIES: 'OPEN_TASKER_PROPERTIES',
    CLOSE_TASKER_PROPERTIES: 'CLOSE_TASKER_PROPERTIES',
    APPLY_TASKER_PROPERTIES: 'APPLY_TASKER_PROPERTIES',

    ////////////////////////////////////////
    // ROUTER
    ROUTER_CHANGE_START: 'ROUTER_CHANGE_START',
    ROUTER_CHANGE_SUCCESS: 'ROUTER_CHANGE_SUCCESS',
    // ROUTER_NOT_FOUND: 'ROUTER_NOT_FOUND',
    // ROUTER_CHANGE_ERROR: 'ROUTER_CHANGE_ERROR',

    ////////////////////////////////////////
    // Communication Instantly
    // widget
    COMMUNICATION_ADD_WIDGET: 'COMMUNICATION_ADD_WIDGET',
    COMMUNICATION_REMOVE_WIDGET: 'COMMUNICATION_REMOVE_WIDGET',
    COMMUNICATION_FULLSIZE_WIDGET: 'COMMUNICATION_FULLSIZE_WIDGET',
    COMMUNICATION_ORIGINALSIZE_WIDGET: 'COMMUNICATION_ORIGINALSIZE_WIDGET',

    COMMUNICATION_SHOW_APP_LIST_FOR_WIDGET: 'COMMUNICATION_SHOW_APP_LIST_FOR_WIDGET',
    COMMUNICATION_SHOW_APP_LIST_FOR_TASKER: 'COMMUNICATION_SHOW_APP_LIST_FOR_TASKER',
    // COMMUNICATION_REFRESH_SYNC_WIDGET: 'COMMUNICATION_REFRESH_SYNC_WIDGET',
    // COMMUNICATION_REFRESH_APPLY_WIDGET: 'COMMUNICATION_REFRESH_APPLY_WIDGET',

    // dashboard
    COMMUNICATION_ADD_DASHBOARD: 'COMMUNICATION_ADD_DASHBOARD',
    COMMUNICATION_REMOVE_DASHBOARD: 'COMMUNICATION_REMOVE_DASHBOARD',


    COMMUNICATION_REMOVE_WORKSPACE: 'COMMUNICATION_REMOVE_WORKSPACE',
    COMMUNICATION_REMOVE_TASKER: 'COMMUNICATION_REMOVE_TASKER',

    ////////////////////////////////////////
    // Notify
    NOTIFY_ERROR: 'NOTIFY_ERROR',
    NOTIFY_SUCCESS: 'NOTIFY_SUCCESS',

    ////////////////////////////////////////
    // Sync Condition
    SYNC_OUT_CONDITION: 'SYNC_OUT_CONDITION',

    ////////////////////////////////////////
    // Context Menu
    SHOW_CONTEXT_MENU: 'SHOW_CONTEXT_MENU',
    CLOSE_CONTEXT_MENU: 'CLOSE_CONTEXT_MENU',

    ////////////////////////////////////////
    // Modal
    SHOW_CONFIRM_MODAL: 'SHOW_CONFIRM_MODAL',
	SHOW_CONFIRM_DELETE_MODAL: 'SHOW_CONFIRM_DELETE_MODAL',
	SHOW_ALERT_MODAL: 'SHOW_ALERT_MODAL',
	SHOW_SHARE_MODAL: 'SHOW_SHARE_MODAL',
	SHOW_WORKSPACE_EDIT_MODAL: 'SHOW_WORKSPACE_EDIT_MODAL',
    SHOW_CONFIGURATION_EDIT_MODAL: 'SHOW_CONFIGURATION_EDIT_MODAL',
    SHOW_APPLY_MODULE_MODAL: 'SHOW_APPLY_MODULE_MODAL',

    ////////////////////////////////////////
    // Push based on Websocket
    PUSH_SHARED_DASHBOARD: 'DS',
    PUSH_SHARED_WORKSPACE: 'WS',
    PUSH_PREDEFINED_DASHBOARD: 'PUSH_PREDEFINED_DASHBOARD',
    PUSH_DELETE_USER: 'US',

    ////////////////////////////////////////
	// Link based on email, notification
    LINK_SAVE_PARAMS: 'LINK_SAVE_PARAMS'
}
