CREATE TABLESPACE MI_DAT DATAFILE 'MI_DAT.dat' SIZE 1024M  AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CREATE TABLESPACE MI_IDX DATAFILE 'MI_IDX.dat' SIZE 1024M  AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CREATE TABLESPACE OWNER_DAT DATAFILE
    '/<db datafile 위치 디렉토리>/owner_dat01.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/owner_dat02.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/owner_dat03.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/owner_dat04.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/owner_dat05.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING PERMANENT;

CREATE TABLESPACE OWNER_IDX DATAFILE
    '/<db datafile 위치 디렉토리>/owner_idx01.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/owner_idx02.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/owner_idx03.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/owner_idx04.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/owner_idx05.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING PERMANENT;

CREATE TABLESPACE OWNER_LOB DATAFILE
    '/<db datafile 위치 디렉토리>/owner_lob01.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/owner_lob02.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/owner_lob03.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/owner_lob04.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/owner_lob05.dbf' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING PERMANENT;​

/*
e.g.
CREATE TABLESPACE NPDM_DAT DATAFILE
  'D:\APP\BISTEL\PRODUCT\11.2.0\DBHOME_1\DATABASE\NPDM_DAT.DAT' SIZE 1024M
  AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED online;

CREATE TABLESPACE NPDM_IDX DATAFILE
  'D:\APP\BISTEL\PRODUCT\11.2.0\DBHOME_1\DATABASE\NPDM_IDX.DAT' SIZE 1024M
  AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED online;

*/