CREATE USER MI IDENTIFIED BY bistel01 DEFAULT TABLESPACE MI_DAT;  

CREATE USER OWNER IDENTIFIED BY bistel01 DEFAULT TABLESPACE OWNER_DAT;

GRANT CONNECT, RESOURCE TO MI, OWNER;

GRANT RESTRICTED SESSION,CREATE SESSION,RESOURCE TO MI;
GRANT RESTRICTED SESSION,CREATE SESSION,RESOURCE TO OWNER;

ALTER USER MI DEFAULT TABLESPACE MI_DAT QUOTA UNLIMITED ON MI_DAT;
ALTER USER MI DEFAULT TABLESPACE MI_IDX QUOTA UNLIMITED ON MI_IDX;

ALTER USER OWNER DEFAULT TABLESPACE OWNER_DAT QUOTA UNLIMITED ON OWNER_DAT;
ALTER USER OWNER DEFAULT TABLESPACE OWNER_IDX QUOTA UNLIMITED ON OWNER_IDX;
ALTER USER OWNER DEFAULT TABLESPACE OWNER_LOB QUOTA UNLIMITED ON OWNER_LOB;


grant create view to PDM;
/*
e.g.
create user npdm identified by bistel01 default tablespace npdm_dat;
grant connect, resource to npdm;

*/