-- CREATE TABLESPACE MI_DAT DATAFILE 'MI_DAT.dat' SIZE 1024M  AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
-- CREATE TABLESPACE MI_IDX DATAFILE 'MI_IDX.dat' SIZE 1024M  AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
-- CREATE USER BISTEL IDENTIFIED BY bistel01 DEFAULT TABLESPACE MI_DAT;  
-- GRANT CONNECT, RESOURCE TO BISTEL;


CREATE SEQUENCE SEQ_APP_A3
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE SEQ_CODE_A3
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE SEQ_CODE_CATEGORY_A3
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE SEQ_DASHBOARD_A3
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       ORDER;

CREATE SEQUENCE SEQ_NOTIFICATION_A3
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE SEQ_TASKER_A3
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE SEQ_TASKER_BEHAVIOR_A3
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE SEQ_TASKER_TYPE_A3
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE SEQ_WIDGET_A3
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE SEQ_WIDGET_TYPE_A3
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE SEQ_WORKSPACE_A3
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       ORDER;

CREATE TABLE APP_A3
(
   APP_ID  NUMBER(20)          NOT NULL,
   NAME    VARCHAR2(50 Byte)
)
TABLESPACE MI_DAT;

ALTER TABLE APP_A3
   ADD CONSTRAINT APP_A3_PK
   PRIMARY KEY (APP_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE CODE_A3
(
   CODE_ID           NUMBER(20)            NOT NULL,
   CODE              VARCHAR2(32 Byte)     NOT NULL,
   NAME              VARCHAR2(50 Byte)     NOT NULL,
   USED              VARCHAR2(1 Byte),
   CODE_ORDER        NUMBER(20),
   CODE_DEFAULT      VARCHAR2(1 Byte),
   DESCRIPTION       VARCHAR2(1024 Byte),
   CODE_CATEGORY_ID  NUMBER(20)            NOT NULL
)
TABLESPACE MI_DAT;

ALTER TABLE CODE_A3
   ADD CONSTRAINT CODE_A3_PK
   PRIMARY KEY (CODE_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE CODE_CATEGORY_A3
(
   CODE_CATEGORY_ID  NUMBER(20)          NOT NULL,
   APP_ID            NUMBER(20)          NOT NULL,
   NAME              VARCHAR2(50 Byte)
)
TABLESPACE MI_DAT;

ALTER TABLE CODE_CATEGORY_A3
   ADD CONSTRAINT CODE_CATEGORY_A3_PK
   PRIMARY KEY (CODE_CATEGORY_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE DASHBOARD_A3
(
   DASHBOARD_ID     NUMBER(20)          NOT NULL,
   TITLE            VARCHAR2(50 Byte),
   DASHBOARD_ORDER  NUMBER(20),
   USER_ID          VARCHAR2(50 Byte),
   CREATE_DTTS      TIMESTAMP(6),
   HOME             VARCHAR2(1 Byte),
   PREDEFINED       VARCHAR2(1 Byte)    DEFAULT 'N'
)
TABLESPACE MI_DAT;

ALTER TABLE DASHBOARD_A3
   ADD CONSTRAINT DASHBOARD_A3_PK
   PRIMARY KEY (DASHBOARD_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE GROUP_ROLE_LNK_A3
(
   CONDITION      VARCHAR2(50 Byte)   DEFAULT '*' NOT NULL,
   USER_GROUP_ID  VARCHAR2(50 Byte)   NOT NULL,
   ROLE_ID        VARCHAR2(50 Byte)   NOT NULL
)
TABLESPACE MI_DAT;

ALTER TABLE GROUP_ROLE_LNK_A3
   ADD CONSTRAINT GROUP_ROLE_LNK_A3_PK
   PRIMARY KEY (USER_GROUP_ID, ROLE_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE INDEX IDX_GROUP_ROLE_LNK_A3_01
   ON GROUP_ROLE_LNK_A3 (ROLE_ID ASC)
   TABLESPACE MI_IDX;


CREATE TABLE NOTIFICATION_A3
(
   NOTIFICATION_ID    NUMBER(20)            NOT NULL,
   SOURCE_USER_ID     VARCHAR2(50 Byte),
   TARGET_USER_ID     VARCHAR2(50 Byte),
   NOTIFICATION_TYPE  VARCHAR2(10 Byte),
   MESSAGE            VARCHAR2(1024 Byte),
   LINK_URL           VARCHAR2(512 Byte),
   DETAIL_VIEW_YN     VARCHAR2(1 Byte)      DEFAULT 'N',
   DETAIL_VIEW_DTTS   TIMESTAMP(6),
   READ_YN            VARCHAR2(1 Byte)      DEFAULT 'N',
   READ_DTTS          TIMESTAMP(6),
   CREATE_DTTS        TIMESTAMP(6),
   UPDATE_DTTS        TIMESTAMP(6),
   SEND_YN            VARCHAR2(1 Byte)
)
TABLESPACE MI_DAT;

ALTER TABLE NOTIFICATION_A3
   ADD CONSTRAINT NOTIFICATION_A3_PK
   PRIMARY KEY (NOTIFICATION_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE ROLE_A3
(
   ROLE_ID      VARCHAR2(50 Byte)     NOT NULL,
   DESCRIPTION  VARCHAR2(1024 Byte)
)
TABLESPACE MI_DAT;

ALTER TABLE ROLE_A3
   ADD CONSTRAINT ROLE_A3_PK
   PRIMARY KEY (ROLE_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE ROLE_TREE_PATHS_A3
(
   ANCESTOR    VARCHAR2(50 Byte)   NOT NULL,
   DESCENDANT  VARCHAR2(50 Byte)   NOT NULL
)
TABLESPACE MI_DAT;

ALTER TABLE ROLE_TREE_PATHS_A3
   ADD CONSTRAINT ROLE_TREE_PATHS_A3_PK
   PRIMARY KEY (ANCESTOR, DESCENDANT) 
   USING INDEX TABLESPACE MI_IDX;

CREATE INDEX IDX_ROLE_TREE_PATHS_A3_01
   ON ROLE_TREE_PATHS_A3 (ANCESTOR ASC)
   TABLESPACE MI_DAT;

CREATE INDEX IDX_ROLE_TREE_PATHS_A3_02
   ON ROLE_TREE_PATHS_A3 (DESCENDANT ASC)
   TABLESPACE MI_DAT;


CREATE TABLE TASKER_A3
(
   TASKER_ID       NUMBER(20)          NOT NULL,
   WORKSPACE_ID    NUMBER(20)          NOT NULL,
   TITLE           VARCHAR2(50 Byte),
   TASKER_TYPE_ID  NUMBER(20)          NOT NULL,
   PARENT_ID       NUMBER(20)
)
TABLESPACE MI_DAT;

ALTER TABLE TASKER_A3
   ADD CONSTRAINT TASKER_A3_PK
   PRIMARY KEY (TASKER_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE TASKER_BEHAVIOR_A3
(
   TASKER_BEHAVIOR_ID         NUMBER(20)          NOT NULL,
   TASKER_ID                  NUMBER(20)          NOT NULL,
   TASKER_BEHAVIOR_TYPE_NAME  VARCHAR2(50 Byte)   NOT NULL,
   STATUS                     VARCHAR2(50 Byte),
   START_DTTS                 TIMESTAMP(6),
   END_DTTS                   TIMESTAMP(6)
)
TABLESPACE MI_DAT;

ALTER TABLE TASKER_BEHAVIOR_A3
   ADD CONSTRAINT TASKER_BEHAVIOR_A3_PK
   PRIMARY KEY (TASKER_BEHAVIOR_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE TASKER_BEHAVIOR_DATA_A3
(
   TASKER_BEHAVIOR_ID  NUMBER(20)   NOT NULL,
   INPUT               CLOB,
   OUTPUT              CLOB
)

NOLOGGING
TABLESPACE MI_DAT;

ALTER TABLE TASKER_BEHAVIOR_DATA_A3
   ADD CONSTRAINT TASKER_BEHAVIOR_DATA_A3_PK
   PRIMARY KEY (TASKER_BEHAVIOR_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE TASKER_BEHAVIOR_TYPE_A3
(
   TASKER_BEHAVIOR_TYPE_NAME  VARCHAR2(50 Byte)     NOT NULL,
   CLASS_TYPE                 VARCHAR2(1024 Byte),
   INPUT_CLASS_TYPE           VARCHAR2(1024 Byte),
   OUTPUT_CLASS_TYPE          VARCHAR2(1024 Byte)
)
TABLESPACE MI_DAT;

ALTER TABLE TASKER_BEHAVIOR_TYPE_A3
   ADD CONSTRAINT TASKER_BEHAVIOR_TYPE_A3_PK
   PRIMARY KEY (TASKER_BEHAVIOR_TYPE_NAME) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE TASKER_CONDITION_A3
(
   TASKER_ID  NUMBER(20)          NOT NULL,
   KEY        VARCHAR2(32 Byte)   NOT NULL,
   VALUE      CLOB
)

TABLESPACE MI_DAT;

ALTER TABLE TASKER_CONDITION_A3
   ADD CONSTRAINT TASKER_CONDITION_A3_PK
   PRIMARY KEY (TASKER_ID, KEY) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE TASKER_PROPERTY_A3
(
   TASKER_ID  NUMBER(20)            NOT NULL,
   KEY        VARCHAR2(32 Byte)     NOT NULL,
   VALUE      VARCHAR2(4000 Byte)
)
TABLESPACE MI_DAT;

ALTER TABLE TASKER_PROPERTY_A3
   ADD CONSTRAINT TASKER_PROPERTY_A3_PK
   PRIMARY KEY (TASKER_ID, KEY) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE TASKER_TREEPATH_A3
(
   ANCESTOR    NUMBER(20)   NOT NULL,
   DESCENDANT  NUMBER(20)   NOT NULL,
   DEPTH       NUMBER(20)
)
TABLESPACE MI_DAT;

ALTER TABLE TASKER_TREEPATH_A3
   ADD CONSTRAINT TASKER_TREEPATH_A3_PK
   PRIMARY KEY (ANCESTOR, DESCENDANT) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE TASKER_TYPE_A3
(
   TASKER_TYPE_ID  NUMBER(20)            NOT NULL,
   NAME            VARCHAR2(32 Byte),
   TITLE           VARCHAR2(50 Byte),
   DESCRIPTION     VARCHAR2(1024 Byte),
   USED            VARCHAR2(1 Byte)
)
TABLESPACE MI_DAT;

ALTER TABLE TASKER_TYPE_A3
   ADD CONSTRAINT TASKER_TYPE_A3_PK
   PRIMARY KEY (TASKER_TYPE_ID) 
   USING INDEX TABLESPACE MI_IDX;

ALTER TABLE TASKER_TYPE_A3
   ADD CONSTRAINT TASKER_TYPE_A3_UK1 UNIQUE (NAME);


CREATE TABLE USER_A3
(
   USER_ID           VARCHAR2(50 Byte)     NOT NULL,
   NAME              VARCHAR2(50 Byte),
   PASSWORD          VARCHAR2(100 Byte),
   EMAIL             VARCHAR2(50 Byte),
   PHONE_NO          VARCHAR2(20 Byte),
   DESCRIPTION       VARCHAR2(1024 Byte),
   DEPARTMENT        VARCHAR2(50 Byte),
   RESPONSIBILITIES  VARCHAR2(50 Byte),
   BIRTHDAY          VARCHAR2(50 Byte),
   POSITION          VARCHAR2(50 Byte),
   TYPE              VARCHAR2(1 Byte),
   COMPANY_PHONE     VARCHAR2(20 Byte),
   SEX               VARCHAR2(50 Byte),
   IMG_URL           VARCHAR2(256 Byte),
   LOCATION          VARCHAR2(1024 Byte)
)
TABLESPACE MI_DAT;

ALTER TABLE USER_A3
   ADD CONSTRAINT USER_A3_PK
   PRIMARY KEY (USER_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE USER_DASHBOARD_LNK_A3
(
   USER_ID          VARCHAR2(50 Byte)   NOT NULL,
   DASHBOARD_ID     NUMBER(20)          NOT NULL,
   HOME             VARCHAR2(1 Byte),
   FAVORITE         VARCHAR2(1 Byte),
   DASHBOARD_ORDER  NUMBER(20)
)
TABLESPACE MI_DAT;

ALTER TABLE USER_DASHBOARD_LNK_A3
   ADD CONSTRAINT USER_DASHBOARD_LNK_A3_PK
   PRIMARY KEY (USER_ID, DASHBOARD_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE USER_GROUP_A3
(
   USER_GROUP_ID  VARCHAR2(50 Byte)     NOT NULL,
   DESCRIPTION    VARCHAR2(1024 Byte),
   TYPE           VARCHAR2(1 Byte)      DEFAULT 'I',
   IMG_URL        VARCHAR2(256 Byte),
   EMAIL          VARCHAR2(256 Byte)
)
TABLESPACE MI_DAT;

ALTER TABLE USER_GROUP_A3
   ADD CONSTRAINT GROUP_A3_PK
   PRIMARY KEY (USER_GROUP_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE USER_GROUP_DASHBOARD_SHARE_A3
(
   USER_GROUP_ID  VARCHAR2(50 Byte)   NOT NULL,
   DASHBOARD_ID   NUMBER(20)          NOT NULL
)
TABLESPACE MI_DAT;

ALTER TABLE USER_GROUP_DASHBOARD_SHARE_A3
   ADD CONSTRAINT UG_DASHBOARD_SHARE_A3_PK
   PRIMARY KEY (USER_GROUP_ID, DASHBOARD_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE USER_GROUP_LNK_A3
(
   USER_ID        VARCHAR2(50 Byte)   NOT NULL,
   USER_GROUP_ID  VARCHAR2(50 Byte)   NOT NULL
)
TABLESPACE MI_DAT;

ALTER TABLE USER_GROUP_LNK_A3
   ADD CONSTRAINT USER_GROUP_LNK_A3_PK
   PRIMARY KEY (USER_ID, USER_GROUP_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE INDEX IDX_USER_GROUP_LNK_A3_01
   ON USER_GROUP_LNK_A3 (USER_GROUP_ID ASC)
   TABLESPACE MI_DAT;


CREATE TABLE USER_GROUP_WORKSPACE_SHARE_A3
(
   USER_GROUP_ID  VARCHAR2(50 Byte)   NOT NULL,
   WORKSPACE_ID   NUMBER(20)          NOT NULL
)
TABLESPACE MI_DAT;

ALTER TABLE USER_GROUP_WORKSPACE_SHARE_A3
   ADD CONSTRAINT UG_WORKSPACE_SHARE_A3_PK
   PRIMARY KEY (USER_GROUP_ID, WORKSPACE_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE USER_WORKSPACE_LNK_A3
(
   USER_ID       VARCHAR2(50 Byte)   NOT NULL,
   WORKSPACE_ID  NUMBER(20)          NOT NULL,
   FAVORITE      VARCHAR2(1 Byte)
)
TABLESPACE MI_DAT;

ALTER TABLE USER_WORKSPACE_LNK_A3
   ADD CONSTRAINT USER_WORKSPACE_LNK_A3_PK
   PRIMARY KEY (USER_ID, WORKSPACE_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE WIDGET_A3
(
   WIDGET_ID       NUMBER(20)          NOT NULL,
   DASHBOARD_ID    NUMBER(20)          NOT NULL,
   TITLE           VARCHAR2(50 Byte),
   X               NUMBER,
   Y               NUMBER,
   WIDTH           NUMBER,
   HEIGHT          NUMBER,
   WIDGET_TYPE_ID  NUMBER(20)          NOT NULL,
   CONDITIONS      CLOB,
   PROPERTIES      CLOB,
   PAGE            NUMBER(10)
)

TABLESPACE MI_DAT;

ALTER TABLE WIDGET_A3
   ADD CONSTRAINT WIDGET_A3_PK
   PRIMARY KEY (WIDGET_ID) 
   USING INDEX TABLESPACE MI_IDX;

CREATE TABLE WIDGET_TYPE_A3
(
   WIDGET_TYPE_ID  NUMBER(20)            NOT NULL,
   NAME            VARCHAR2(50 Byte)     NOT NULL,
   TITLE           VARCHAR2(50 Byte),
   THUMBNAIL       VARCHAR2(1024 Byte),
   DESCRIPTION     VARCHAR2(1024 Byte),
   WIDTH           NUMBER,
   HEIGHT          NUMBER,
   CATEGORY        VARCHAR2(50 Byte),
   PROPERTIES      VARCHAR2(4000 Byte),
   USED            VARCHAR2(1 Byte)
)
TABLESPACE MI_DAT;

ALTER TABLE WIDGET_TYPE_A3
   ADD CONSTRAINT WIDGET_TYPE_A3_PK
   PRIMARY KEY (WIDGET_TYPE_ID) 
   USING INDEX TABLESPACE MI_IDX;

ALTER TABLE WIDGET_TYPE_A3
   ADD CONSTRAINT WIDGET_TYPE_A3_UK1 UNIQUE (NAME);


CREATE TABLE WORKSPACE_A3
(
   WORKSPACE_ID      NUMBER(20)            NOT NULL,
   USER_ID           VARCHAR2(50 Byte),
   TITLE             VARCHAR2(50 Byte),
   DESCRIPTION       VARCHAR2(1024 Byte),
   AUTO_CREATION_YN  CHAR(1)               DEFAULT 'N',
   CREATE_DTTS       TIMESTAMP(6),
   UPDATE_DTTS       TIMESTAMP(6)
)
TABLESPACE MI_DAT;

ALTER TABLE WORKSPACE_A3
   ADD CONSTRAINT WORKSPACE_A3_PK
   PRIMARY KEY (WORKSPACE_ID) 
   USING INDEX TABLESPACE MI_IDX;














ALTER TABLE CODE_A3
  ADD CONSTRAINT CODE_A3_FK FOREIGN KEY (CODE_CATEGORY_ID)
  REFERENCES CODE_CATEGORY_A3 (CODE_CATEGORY_ID);

ALTER TABLE CODE_CATEGORY_A3
  ADD CONSTRAINT CODE_CATEGORY_A3_FK FOREIGN KEY (APP_ID)
  REFERENCES APP_A3 (APP_ID);

ALTER TABLE GROUP_ROLE_LNK_A3
  ADD CONSTRAINT GROUP_ROLE_LNK_A3_FK02 FOREIGN KEY (ROLE_ID)
  REFERENCES ROLE_A3 (ROLE_ID);

ALTER TABLE GROUP_ROLE_LNK_A3
  ADD CONSTRAINT GROUP_ROLE_LNK_A3_FK01 FOREIGN KEY (USER_GROUP_ID)
  REFERENCES USER_GROUP_A3 (USER_GROUP_ID);

ALTER TABLE ROLE_TREE_PATHS_A3
  ADD CONSTRAINT ROLE_TREE_PATHS_A3_FK02 FOREIGN KEY (DESCENDANT)
  REFERENCES ROLE_A3 (ROLE_ID);

ALTER TABLE ROLE_TREE_PATHS_A3
  ADD CONSTRAINT ROLE_TREE_PATHS_A3_FK01 FOREIGN KEY (ANCESTOR)
  REFERENCES ROLE_A3 (ROLE_ID);

ALTER TABLE TASKER_A3
  ADD CONSTRAINT TASKER_A3_FK3 FOREIGN KEY (PARENT_ID)
  REFERENCES TASKER_A3 (TASKER_ID)  
  ON DELETE SET NULL;

ALTER TABLE TASKER_A3
  ADD CONSTRAINT TASKER_A3_FK2 FOREIGN KEY (TASKER_TYPE_ID)
  REFERENCES TASKER_TYPE_A3 (TASKER_TYPE_ID);

ALTER TABLE TASKER_A3
  ADD CONSTRAINT TASKER_A3_FK1 FOREIGN KEY (WORKSPACE_ID)
  REFERENCES WORKSPACE_A3 (WORKSPACE_ID);

ALTER TABLE TASKER_BEHAVIOR_A3
  ADD CONSTRAINT TASKER_BEHAVIOR_A3_FK1 FOREIGN KEY (TASKER_ID)
  REFERENCES TASKER_A3 (TASKER_ID)  
  ON DELETE SET NULL;

ALTER TABLE TASKER_BEHAVIOR_A3
  ADD CONSTRAINT TASKER_BEHAVIOR_A3_FK2 FOREIGN KEY (TASKER_BEHAVIOR_TYPE_NAME)
  REFERENCES TASKER_BEHAVIOR_TYPE_A3 (TASKER_BEHAVIOR_TYPE_NAME);

ALTER TABLE TASKER_BEHAVIOR_DATA_A3
  ADD CONSTRAINT TASKER_BEHAVIOR_DATA_A3_FK FOREIGN KEY (TASKER_BEHAVIOR_ID)
  REFERENCES TASKER_BEHAVIOR_A3 (TASKER_BEHAVIOR_ID);

ALTER TABLE TASKER_CONDITION_A3
  ADD CONSTRAINT TASKER_CONDITION_A3_FK FOREIGN KEY (TASKER_ID)
  REFERENCES TASKER_A3 (TASKER_ID);

ALTER TABLE TASKER_PROPERTY_A3
  ADD CONSTRAINT TASKER_PROPERTY_A3_FK FOREIGN KEY (TASKER_ID)
  REFERENCES TASKER_A3 (TASKER_ID);

ALTER TABLE TASKER_TREEPATH_A3
  ADD CONSTRAINT TASKER_TREEPATH_A3_FK2 FOREIGN KEY (DESCENDANT)
  REFERENCES TASKER_A3 (TASKER_ID);

ALTER TABLE TASKER_TREEPATH_A3
  ADD CONSTRAINT TASKER_TREEPATH_A3_FK1 FOREIGN KEY (ANCESTOR)
  REFERENCES TASKER_A3 (TASKER_ID);

ALTER TABLE USER_DASHBOARD_LNK_A3
  ADD CONSTRAINT USER_DASHBOARD_LNK_A3_FK2 FOREIGN KEY (DASHBOARD_ID)
  REFERENCES DASHBOARD_A3 (DASHBOARD_ID);

ALTER TABLE USER_DASHBOARD_LNK_A3
  ADD CONSTRAINT USER_DASHBOARD_LNK_A3_FK1 FOREIGN KEY (USER_ID)
  REFERENCES USER_A3 (USER_ID);

ALTER TABLE USER_GROUP_DASHBOARD_SHARE_A3
  ADD CONSTRAINT UG_DASHBOARD_SHARE_A3_FK2 FOREIGN KEY (DASHBOARD_ID)
  REFERENCES DASHBOARD_A3 (DASHBOARD_ID);

ALTER TABLE USER_GROUP_DASHBOARD_SHARE_A3
  ADD CONSTRAINT UG_DASHBOARD_SHARE_A3_FK1 FOREIGN KEY (USER_GROUP_ID)
  REFERENCES USER_GROUP_A3 (USER_GROUP_ID);

ALTER TABLE USER_GROUP_WORKSPACE_SHARE_A3
  ADD CONSTRAINT UG_WORKSPACE_SHARE_A3_FK1 FOREIGN KEY (USER_GROUP_ID)
  REFERENCES USER_GROUP_A3 (USER_GROUP_ID);

ALTER TABLE USER_GROUP_WORKSPACE_SHARE_A3
  ADD CONSTRAINT UG_WORKSPACE_SHARE_A3_PK2 FOREIGN KEY (WORKSPACE_ID)
  REFERENCES WORKSPACE_A3 (WORKSPACE_ID);

ALTER TABLE USER_WORKSPACE_LNK_A3
  ADD CONSTRAINT USER_WORKSPACE_LNK_A3_FK1 FOREIGN KEY (USER_ID)
  REFERENCES USER_A3 (USER_ID);

ALTER TABLE USER_WORKSPACE_LNK_A3
  ADD CONSTRAINT USER_WORKSPACE_LNK_A3_FK2 FOREIGN KEY (WORKSPACE_ID)
  REFERENCES WORKSPACE_A3 (WORKSPACE_ID);

ALTER TABLE WIDGET_A3
  ADD CONSTRAINT WIDGET_A3_FK1 FOREIGN KEY (DASHBOARD_ID)
  REFERENCES DASHBOARD_A3 (DASHBOARD_ID);

ALTER TABLE WIDGET_A3
  ADD CONSTRAINT WIDGET_A3_FK2 FOREIGN KEY (WIDGET_TYPE_ID)
  REFERENCES WIDGET_TYPE_A3 (WIDGET_TYPE_ID);
