
/*
    sequence
*/

CREATE SEQUENCE seq_code_mst_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_area_mst_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_eqp_mst_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_param_mst_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_parts_mst_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_bearing_mst_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_manual_rpm_mst_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_trace_spec_mst_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_trace_trx_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_trace_raw_trx_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_alarm_trx_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_eqp_alarm_daily_sum_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;

CREATE SEQUENCE seq_trace_daily_sum_pdm
       INCREMENT BY 1
       NOMINVALUE
       NOMAXVALUE
       CACHE 20
       NOCYCLE
       NOORDER;



/*
    tables
*/


-- drop table ALARM_TRX_PDM cascade constraints PURGE;
-- drop table AREA_MST_PDM cascade constraints PURGE;
-- drop table BEARING_MST_PDM cascade constraints PURGE;
-- drop table CODE_MST_PDM cascade constraints PURGE;
-- drop table EQP_ALARM_DAILY_SUM_PDM cascade constraints PURGE;
-- drop table EQP_MST_PDM cascade constraints PURGE;
-- drop table MANUAL_RPM_MST_PDM cascade constraints PURGE;
-- drop table PARAM_MST_PDM cascade constraints PURGE;
-- drop table PARTS_MST_PDM cascade constraints PURGE;
-- drop table TRACE_DAILY_SUM_PDM cascade constraints PURGE;
-- drop table TRACE_RAW_TRX_PDM cascade constraints PURGE;
-- drop table TRACE_SPEC_MST_PDM cascade constraints PURGE;
-- drop table TRACE_TRX_PDM cascade constraints PURGE;


CREATE TABLE CODE_MST_PDM
(
    RAWID           NUMBER(10)      NOT NULL,
    CATEGORY        VARCHAR2(32)    NOT NULL,
    CODE            VARCHAR2(32)    NOT NULL,
    NAME            VARCHAR2(64)    NOT NULL,
    USED_YN         CHAR(1)         DEFAULT 'Y',
    DEFAULT_YN      CHAR(1)         DEFAULT 'N',
    ORDERING        NUMBER(10)      NULL,
    DESCRIPTION     VARCHAR2(2048)  NULL,
    CREATE_BY       VARCHAR(32)     NULL,
	CREATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
	UPDATE_BY       VARCHAR(32)     NULL,
	UPDATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_CODE_MST_PDM ON CODE_MST_PDM (RAWID)	TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_CODE_MST_PDM ON CODE_MST_PDM (CATEGORY, CODE, NAME) TABLESPACE NPDM_IDX;


CREATE TABLE AREA_MST_PDM
(
    RAWID           NUMBER(10)      NOT NULL,
	NAME            VARCHAR2(128)   NOT NULL,
	DESCRIPTION     VARCHAR2(2048)  NULL,
	PARENT_RAWID    NUMBER(10)      DEFAULT 0,
	CREATE_BY       VARCHAR(32)     NULL,
	CREATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
	UPDATE_BY       VARCHAR(32)     NULL,
	UPDATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_AREA_MST_PDM ON AREA_MST_PDM (RAWID)	TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_AREA_MST_PDM ON AREA_MST_PDM (NAME) TABLESPACE NPDM_IDX;



CREATE TABLE EQP_MST_PDM
(
    RAWID           NUMBER(10)      NOT NULL,
    AREA_MST_RAWID  NUMBER(10)      NOT NULL,
	NAME            VARCHAR2(128)   NOT NULL,
	DESCRIPTION     VARCHAR2(2048)  NULL,
	DATA_TYPE_CD    VARCHAR2(32)    DEFAULT 'STD',
	IMAGE           BLOB            NULL,
	CREATE_BY       VARCHAR(32)     NULL,
	CREATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
	UPDATE_BY       VARCHAR(32)     NULL,
	UPDATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_EQP_MST_PDM ON EQP_MST_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_EQP_MST_PDM ON EQP_MST_PDM (AREA_MST_RAWID, NAME) TABLESPACE NPDM_IDX;

CREATE TABLE BEARING_MST_PDM
(
    RAWID           NUMBER(10)      NOT NULL,
    MODEL_NUMBER    VARCHAR2(128)   NOT NULL,
    MANUFACTURE     VARCHAR2(128)   NOT NULL,
	BPFO            INT             NULL,
	BPFI            INT             NULL,
	BSF             INT             NULL,
	FTF             INT             NULL,
	DESCRIPTION     VARCHAR2(2048)  NULL,
	CREATE_BY       VARCHAR(32)     NULL,
	CREATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
	UPDATE_BY       VARCHAR(32)     NULL,
	UPDATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_BEARING_MST_PDM ON BEARING_MST_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_BEARING_MST_PDM ON BEARING_MST_PDM (MODEL_NUMBER, MANUFACTURE) TABLESPACE NPDM_IDX;


CREATE TABLE PARTS_MST_PDM
(
    RAWID               NUMBER(10)      NOT NULL,
    EQP_MST_RAWID       NUMBER(10)      NOT NULL,
    BEARING_MST_RAWID   NUMBER(10)      NULL,
	NAME                VARCHAR2(256)   NOT NULL,
	PARTS_TYPE_CD       VARCHAR2(32)    NOT NULL,
	RPM                 NUMBER(5, 0)    NULL,
	RATIO               NUMBER(10, 2)   NOT NULL,
	BASE_RATIO_YN       CHAR(1)         DEFAULT 'N',
	CREATE_BY           VARCHAR(32)     NULL,
	CREATE_DTTS         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
	UPDATE_BY           VARCHAR(32)     NULL,
	UPDATE_DTTS         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_PARTS_MST_PDM ON PARTS_MST_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_PARTS_MST_PDM ON PARTS_MST_PDM (EQP_MST_RAWID, NAME)	TABLESPACE NPDM_IDX;


CREATE TABLE PARAM_MST_PDM
(
    RAWID           NUMBER(10)      NOT NULL,
    EQP_MST_RAWID   NUMBER(10)      NOT NULL,
    PARTS_MST_RAWID NUMBER(10)      NOT NULL,
	NAME            VARCHAR2(256)   NOT NULL,
	DESCRIPTION     VARCHAR2(2048)  NULL,
	PARAM_TYPE_CD   VARCHAR2(32)    NOT NULL,
	UNIT_CD         VARCHAR2(32)    NOT NULL,
	CREATE_BY       VARCHAR(32)     NULL,
	CREATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
	UPDATE_BY       VARCHAR(32)     NULL,
	UPDATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_PARAM_MST_PDM ON PARAM_MST_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_PARAM_MST_PDM ON PARAM_MST_PDM (EQP_MST_RAWID, NAME) TABLESPACE NPDM_IDX;



CREATE TABLE TRACE_SPEC_MST_PDM
(
	RAWID           NUMBER(10)      NOT NULL,
	PARAM_MST_RAWID NUMBER(10)      NOT NULL,
	ALARM_SPEC      FLOAT(23)       NOT NULL,
	WARNING_SPEC    FLOAT(23)       NOT NULL,
	CREATE_BY       VARCHAR(32)     NULL,
	CREATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
	UPDATE_BY       VARCHAR(32)     NULL,
	UPDATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_TRACE_SPEC_MST_PDM ON TRACE_SPEC_MST_PDM (RAWID)	TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_TRACE_SPEC_MST_PDM ON TRACE_SPEC_MST_PDM (PARAM_MST_RAWID) TABLESPACE NPDM_IDX;



CREATE TABLE MANUAL_RPM_MST_PDM
(
    RAWID           NUMBER(10)      NOT NULL,
    PARAM_MST_RAWID NUMBER(10)      NOT NULL,
    RPM             NUMBER(5,2)     NULL,
    CREATE_BY       VARCHAR(32)     NULL,
	CREATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
	UPDATE_BY       VARCHAR(32)     NULL,
	UPDATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT;

CREATE UNIQUE INDEX PK_MANUAL_RPM_MST_PDM ON MANUAL_RPM_MST_PDM (RAWID)	TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_MANUAL_RPM_MST_PDM ON MANUAL_RPM_MST_PDM (PARAM_MST_RAWID) TABLESPACE NPDM_IDX;



CREATE TABLE TRACE_TRX_PDM
(
    RAWID           NUMBER(20)      NOT NULL,
    PARAM_MST_RAWID NUMBER(10)      NOT NULL,
    VALUE           FLOAT           NOT NULL,
    RPM             NUMBER(5,2)     NULL,
    ALARM_SPEC      FLOAT           NULL,
    WARNING_SPEC    FLOAT           NULL,
    EVENT_DTTS      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    RESERVED_COL1   VARCHAR(128)    NULL,
    RESERVED_COL2   VARCHAR(128)    NULL,
    RESERVED_COL3   VARCHAR(128)    NULL,
    RESERVED_COL4   VARCHAR(128)    NULL,
    RESERVED_COL5   VARCHAR(128)    NULL
)
TABLESPACE NPDM_DAT
PARTITION BY RANGE (EVENT_DTTS)
   (PARTITION P_201712 VALUES LESS THAN (to_timestamp('201801', 'YYYYMM')),
	PARTITION P_201801 VALUES LESS THAN (to_timestamp('201802', 'YYYYMM')),
	PARTITION P_201802 VALUES LESS THAN (to_timestamp('201803', 'YYYYMM')),
	PARTITION P_201803 VALUES LESS THAN (to_timestamp('201804', 'YYYYMM')),
	PARTITION P_201804 VALUES LESS THAN (to_timestamp('201805', 'YYYYMM')),
	PARTITION P_201805 VALUES LESS THAN (to_timestamp('201806', 'YYYYMM')),
	PARTITION P_201806 VALUES LESS THAN (to_timestamp('201807', 'YYYYMM')),
	PARTITION P_201807 VALUES LESS THAN (to_timestamp('201808', 'YYYYMM')),
	PARTITION P_201808 VALUES LESS THAN (to_timestamp('201809', 'YYYYMM')),
	PARTITION P_201809 VALUES LESS THAN (to_timestamp('201810', 'YYYYMM')),
	PARTITION P_201810 VALUES LESS THAN (to_timestamp('201811', 'YYYYMM')));

CREATE UNIQUE INDEX PK_TRACE_TRX_PDM ON TRACE_TRX_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_TRACE_TRX_PDM ON TRACE_TRX_PDM (EVENT_DTTS, PARAM_MST_RAWID) TABLESPACE NPDM_IDX;

-- 파티션 추가
--ALTER TABLE TRACE_TRX_PDM ADD PARTITION P_20180501 VALUES LESS THAN (to_timestamp('2018-05-02 00:00:00', 'YYYY-MM-dd HH24:mi:ss')) //TABLESPACE PTS_11;


CREATE TABLE TRACE_RAW_TRX_PDM
(
    RAWID           NUMBER(20)      NOT NULL,
    PARAM_MST_RAWID NUMBER(10)      NOT NULL,
    TRACE_TRX_RAWID NUMBER(20)      NOT NULL,
    DATA_TYPE_CD    VARCHAR2(32)    NOT NULL,
    MAX_FREQ        INT             NULL,
    FREQ_COUNT      INT             NULL,
    RPM             NUMBER(5,2)     NULL,
    SAMPLING_TIME   FLOAT           NULL,
    BINARY_DATA     BLOB            NULL,
    EVENT_DTTS      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    RESERVED_COL1   VARCHAR(128)    NULL,
    RESERVED_COL2   VARCHAR(128)    NULL,
    RESERVED_COL3   VARCHAR(128)    NULL,
    RESERVED_COL4   VARCHAR(128)    NULL,
    RESERVED_COL5   VARCHAR(128)    NULL
)
TABLESPACE NPDM_DAT
PARTITION BY RANGE (EVENT_DTTS)
   (PARTITION P_201712 VALUES LESS THAN (to_timestamp('201801', 'YYYYMM')),
	PARTITION P_201801 VALUES LESS THAN (to_timestamp('201802', 'YYYYMM')),
	PARTITION P_201802 VALUES LESS THAN (to_timestamp('201803', 'YYYYMM')),
	PARTITION P_201803 VALUES LESS THAN (to_timestamp('201804', 'YYYYMM')),
	PARTITION P_201804 VALUES LESS THAN (to_timestamp('201805', 'YYYYMM')),
	PARTITION P_201805 VALUES LESS THAN (to_timestamp('201806', 'YYYYMM')),
	PARTITION P_201806 VALUES LESS THAN (to_timestamp('201807', 'YYYYMM')),
	PARTITION P_201807 VALUES LESS THAN (to_timestamp('201808', 'YYYYMM')),
	PARTITION P_201808 VALUES LESS THAN (to_timestamp('201809', 'YYYYMM')),
	PARTITION P_201809 VALUES LESS THAN (to_timestamp('201810', 'YYYYMM')),
	PARTITION P_201810 VALUES LESS THAN (to_timestamp('201811', 'YYYYMM')));

CREATE UNIQUE INDEX PK_TRACE_RAW_TRX_PDM ON TRACE_RAW_TRX_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_TRACE_RAW_TRX_PDM ON TRACE_RAW_TRX_PDM (EVENT_DTTS, PARAM_MST_RAWID, TRACE_TRX_RAWID, DATA_TYPE_CD) TABLESPACE NPDM_IDX;



-- 파티션 추가
--ALTER TABLE TRACE_RAW_TRX_PDM ADD PARTITION P_20180501 VALUES LESS THAN (to_timestamp('2018-05-02 00:00:00', 'YYYY-MM-dd HH24:mi:ss')) //TABLESPACE PTS_11;

CREATE TABLE ALARM_TRX_PDM
(
    RAWID           NUMBER(20)      NOT NULL,
    PARAM_MST_RAWID NUMBER(10)      NOT NULL,
    ALARM_TYPE_CD   VARCHAR2(32)    NOT NULL,
    VALUE           FLOAT(23)       NOT NULL,
    ALARM_SPEC      FLOAT(23)       NULL,
    WARNING_SPEC    FLOAT(23)       NULL,
    ALARM_DTTS      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT
PARTITION BY RANGE (ALARM_DTTS)
   (PARTITION P_201801 VALUES LESS THAN (to_timestamp('201802', 'YYYYMM')),
	PARTITION P_201802 VALUES LESS THAN (to_timestamp('201803', 'YYYYMM')),
	PARTITION P_201803 VALUES LESS THAN (to_timestamp('201804', 'YYYYMM')),
	PARTITION P_201804 VALUES LESS THAN (to_timestamp('201805', 'YYYYMM')),
	PARTITION P_201805 VALUES LESS THAN (to_timestamp('201806', 'YYYYMM')),
	PARTITION P_201806 VALUES LESS THAN (to_timestamp('201807', 'YYYYMM')),
	PARTITION P_201807 VALUES LESS THAN (to_timestamp('201808', 'YYYYMM')),
	PARTITION P_201808 VALUES LESS THAN (to_timestamp('201809', 'YYYYMM')),
	PARTITION P_201809 VALUES LESS THAN (to_timestamp('201810', 'YYYYMM')),
	PARTITION P_201810 VALUES LESS THAN (to_timestamp('201811', 'YYYYMM')),
	PARTITION P_201811 VALUES LESS THAN (to_timestamp('201812', 'YYYYMM')));

CREATE UNIQUE INDEX PK_ALARM_TRX_PDM ON ALARM_TRX_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_ALARM_TRX_PDM ON ALARM_TRX_PDM (ALARM_DTTS, PARAM_MST_RAWID) TABLESPACE NPDM_IDX;



-- 파티션 추가
--ALTER TABLE ALARM_TRX_PDM ADD PARTITION P_201812 VALUES LESS THAN ('201901') //TABLESPACE PTS_11;

CREATE TABLE TRACE_DAILY_SUM_PDM
(
	RAWID           NUMBER(10)      NOT NULL,
	PARAM_MST_RAWID NUMBER(10)      NOT NULL,
	ALARM_SPEC      FLOAT(23),
	WARNING_SPEC    FLOAT(23),
	SUM_DTTS        TIMESTAMP(6)    NOT NULL,
    AVG_PERIOD      FLOAT(23),
	AVG_DAILY       FLOAT(23),
	AVG_OOS         FLOAT(23),
	VARIATION       FLOAT(23),
	CAUSE	        VARCHAR2(2048 BYTE),
	CREATE_BY       VARCHAR(32)     NULL,
	CREATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT
PARTITION BY RANGE (SUM_DTTS)
   (PARTITION P_201801 VALUES LESS THAN (to_timestamp('201802', 'YYYYMM')),
	PARTITION P_201802 VALUES LESS THAN (to_timestamp('201803', 'YYYYMM')),
	PARTITION P_201803 VALUES LESS THAN (to_timestamp('201804', 'YYYYMM')),
	PARTITION P_201804 VALUES LESS THAN (to_timestamp('201805', 'YYYYMM')),
	PARTITION P_201805 VALUES LESS THAN (to_timestamp('201806', 'YYYYMM')),
	PARTITION P_201806 VALUES LESS THAN (to_timestamp('201807', 'YYYYMM')),
	PARTITION P_201807 VALUES LESS THAN (to_timestamp('201808', 'YYYYMM')),
	PARTITION P_201808 VALUES LESS THAN (to_timestamp('201809', 'YYYYMM')),
	PARTITION P_201809 VALUES LESS THAN (to_timestamp('201810', 'YYYYMM')),
	PARTITION P_201810 VALUES LESS THAN (to_timestamp('201811', 'YYYYMM')),
	PARTITION P_201811 VALUES LESS THAN (to_timestamp('201812', 'YYYYMM')));

CREATE UNIQUE INDEX PK_TRACE_DAILY_SUM_PDM ON TRACE_DAILY_SUM_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_TRACE_DAILY_SUM_PDM ON TRACE_DAILY_SUM_PDM (SUM_DTTS, PARAM_MST_RAWID) TABLESPACE NPDM_IDX;


CREATE TABLE EQP_ALARM_DAILY_SUM_PDM
(
    RAWID           NUMBER(10)      NOT NULL,
    EQP_MST_RAWID   NUMBER(10)      NOT NULL,
    SUM_DTTS        TIMESTAMP(6)    NOT NULL,
    STATUS_CD       NUMBER(10)      NOT NULL,
	VALUE           FLOAT(23)       NOT NULL,
	CREATE_BY       VARCHAR(32)     NULL,
	CREATE_DTTS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE NPDM_DAT
PARTITION BY RANGE (SUM_DTTS)
   (PARTITION P_201801 VALUES LESS THAN (to_timestamp('201802', 'YYYYMM')),
	PARTITION P_201802 VALUES LESS THAN (to_timestamp('201803', 'YYYYMM')),
	PARTITION P_201803 VALUES LESS THAN (to_timestamp('201804', 'YYYYMM')),
	PARTITION P_201804 VALUES LESS THAN (to_timestamp('201805', 'YYYYMM')),
	PARTITION P_201805 VALUES LESS THAN (to_timestamp('201806', 'YYYYMM')),
	PARTITION P_201806 VALUES LESS THAN (to_timestamp('201807', 'YYYYMM')),
	PARTITION P_201807 VALUES LESS THAN (to_timestamp('201808', 'YYYYMM')),
	PARTITION P_201808 VALUES LESS THAN (to_timestamp('201809', 'YYYYMM')),
	PARTITION P_201809 VALUES LESS THAN (to_timestamp('201810', 'YYYYMM')),
	PARTITION P_201810 VALUES LESS THAN (to_timestamp('201811', 'YYYYMM')),
	PARTITION P_201811 VALUES LESS THAN (to_timestamp('201812', 'YYYYMM')));

CREATE UNIQUE INDEX PK_EQP_ALARM_DAILY_SUM_PDM ON EQP_ALARM_DAILY_SUM_PDM (RAWID) TABLESPACE NPDM_IDX;
CREATE UNIQUE INDEX UK_EQP_ALARM_DAILY_SUM_PDM ON EQP_ALARM_DAILY_SUM_PDM (SUM_DTTS, EQP_MST_RAWID, STATUS_CD) TABLESPACE NPDM_IDX;


