
CREATE SEQUENCE seq_area_pdm;



CREATE SEQUENCE seq_eqp_pdm;



CREATE SEQUENCE seq_measure_trx_pdm;



CREATE SEQUENCE seq_param_pdm;



CREATE SEQUENCE seq_part_pdm;



CREATE SEQUENCE seq_part_type_pdm;



CREATE TABLE ALARM_TRX_PDM
(
	PARAM_ID              NUMBER(10)  NOT NULL ,
	ALARM_DTTS            TIMESTAMP  NOT NULL ,
	ALARM                 FLOAT(23)  NULL ,
	WARN                  FLOAT(23)  NULL ,
	STATUS_CD             NUMBER(10)  NULL ,
	LVL                   FLOAT(23)  NULL ,
	VALUE                 FLOAT(23)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_ALARM_TRX_PDM ON ALARM_TRX_PDM
(PARAM_ID  ASC,ALARM_DTTS  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE ALARM_TRX_PDM
	ADD CONSTRAINT  PK_ALARM_TRX_PDM PRIMARY KEY (PARAM_ID,ALARM_DTTS);



CREATE TABLE AREA_PDM
(
	AREA_ID               NUMBER(10)  NOT NULL ,
	NAME                  VARCHAR2(128)  NULL ,
	DESCRIPTION           VARCHAR2(1024)  NULL ,
	PARENT_ID             NUMBER(10)  NULL ,
	SORT_ORDER            NUMBER(3)   DEFAULT  0 NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_AREA_PDM ON AREA_PDM
(AREA_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE AREA_PDM
	ADD CONSTRAINT  PK_AREA_PDM PRIMARY KEY (AREA_ID);



CREATE TABLE BATCH_JOB_HST_PDM
(
	JOB_DTTS              TIMESTAMP  NOT NULL ,
	JOB_CD                VARCHAR2(32)  NOT NULL ,
	EQP_ID                NUMBER(10)  NULL ,
	JOB_STATUS_CD         VARCHAR2(32)  NULL ,
	JOB_TYPE_CD           VARCHAR2(32)  NULL ,
	UPDATE_DTTS           TIMESTAMP  NULL ,
	UPDATE_USER_ID        VARCHAR2(50)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_BATCH_JOB_HST_PDM ON BATCH_JOB_HST_PDM
(JOB_DTTS  ASC,JOB_CD  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE BATCH_JOB_HST_PDM
	ADD CONSTRAINT  PK_BATCH_JOB_HST_PDM PRIMARY KEY (JOB_DTTS,JOB_CD);



CREATE TABLE BEARING_PDM
(
	MODEL_NUMBER          VARCHAR2(128)  NOT NULL ,
	MANUFACTURE           VARCHAR2(128)  NOT NULL ,
	DESCRIPTION           VARCHAR2(1024)  NULL ,
	BPFO                  NUMBER(10,2)  NULL ,
	BPFI                  NUMBER(10,2)  NULL ,
	BSF                   NUMBER(10,2)  NULL ,
	FTF                   NUMBER(10,2)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_BEARING_PDM ON BEARING_PDM
(MODEL_NUMBER  ASC,MANUFACTURE  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE BEARING_PDM
	ADD CONSTRAINT  PK_BEARING_PDM PRIMARY KEY (MODEL_NUMBER,MANUFACTURE);



CREATE TABLE EQP_ALARM_TRX_PDM
(
	EQP_ID                NUMBER(10)  NOT NULL ,
	ALARM_DTTS            TIMESTAMP  NOT NULL ,
	STATUS_CD             NUMBER(10)  NULL ,
	VALUE                 FLOAT(23)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_EQP_ALARM_TRX_PDM ON EQP_ALARM_TRX_PDM
(EQP_ID  ASC,ALARM_DTTS  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE EQP_ALARM_TRX_PDM
	ADD CONSTRAINT  PK_EQP_ALARM_TRX_PDM PRIMARY KEY (EQP_ID,ALARM_DTTS);



CREATE TABLE EQP_ETC_PDM
(
	EQP_ID                NUMBER(10)  NOT NULL ,
	IMAGE                 BLOB  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_EQP_ETC_PDM ON EQP_ETC_PDM
(EQP_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE EQP_ETC_PDM
	ADD CONSTRAINT  PK_EQP_ETC_PDM PRIMARY KEY (EQP_ID);



CREATE TABLE EQP_PDM
(
	EQP_ID                NUMBER(10)  NOT NULL ,
	NAME                  VARCHAR2(128)  NULL ,
	DESCRIPTION           VARCHAR2(1024)  NULL ,
	SORT_ORDER            NUMBER(3)   DEFAULT  0 NULL ,
	AREA_ID               NUMBER(10)  NOT NULL ,
	DATA_TYPE             VARCHAR2(32)   DEFAULT  'STD' NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_EQP_PDM ON EQP_PDM
(EQP_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE EQP_PDM
	ADD CONSTRAINT  PK_EQP_PDM PRIMARY KEY (EQP_ID);



CREATE TABLE FEATURE_TRX_PDM
(
	MEASURE_TRX_ID        NUMBER(10)  NOT NULL ,
	PEAK                  FLOAT(23)  NULL ,
	RMS                   FLOAT(23)  NULL ,
	SKEWNESS              FLOAT(23)  NULL ,
	KURTOSIS              FLOAT(23)  NULL ,
	CREST                 FLOAT(23)  NULL ,
	CLEARANCE             FLOAT(23)  NULL ,
	IMPULSE               FLOAT(23)  NULL ,
	SHAPE                 FLOAT(23)  NULL ,
	OVERALL               FLOAT(23)  NULL ,
	CREATE_DTTS           TIMESTAMP  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_FEATURE_TRX_PDM ON FEATURE_TRX_PDM
(MEASURE_TRX_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE FEATURE_TRX_PDM
	ADD CONSTRAINT  PK_FEATURE_TRX_PDM PRIMARY KEY (MEASURE_TRX_ID);



CREATE TABLE HEALTH_DAILY_TRX_PDM
(
	EQP_ID                NUMBER(10)  NOT NULL ,
	MEASURE_DTTS          TIMESTAMP  NOT NULL ,
	VALUE                 FLOAT(23)  NULL ,
	SCORE                 FLOAT(23)  NULL 
)
	TABLESPACE OWNER_DAT
	PARTITION BY RANGE (MEASURE_DTTS)
	(PARTITION P_201601 VALUES LESS THAN (to_timestamp('201602', 'YYYYMM')),
	PARTITION P_201602 VALUES LESS THAN (to_timestamp('201603', 'YYYYMM')),
	PARTITION P_201603 VALUES LESS THAN (to_timestamp('201604', 'YYYYMM')),
	PARTITION P_201604 VALUES LESS THAN (to_timestamp('201605', 'YYYYMM')),
	PARTITION P_201605 VALUES LESS THAN (to_timestamp('201606', 'YYYYMM')),
	PARTITION P_201606 VALUES LESS THAN (to_timestamp('201607', 'YYYYMM')),
	PARTITION P_201607 VALUES LESS THAN (to_timestamp('201608', 'YYYYMM')),
	PARTITION P_201608 VALUES LESS THAN (to_timestamp('201609', 'YYYYMM')),
	PARTITION P_201609 VALUES LESS THAN (to_timestamp('201610', 'YYYYMM')),
	PARTITION P_201610 VALUES LESS THAN (to_timestamp('201611', 'YYYYMM')),
	PARTITION P_201611 VALUES LESS THAN (to_timestamp('201612', 'YYYYMM')),
	PARTITION P_201612 VALUES LESS THAN (to_timestamp('201701', 'YYYYMM')),
	PARTITION P_201701 VALUES LESS THAN (to_timestamp('201702', 'YYYYMM')),
	PARTITION P_201702 VALUES LESS THAN (to_timestamp('201703', 'YYYYMM')),
	PARTITION P_201703 VALUES LESS THAN (to_timestamp('201704', 'YYYYMM')),
	PARTITION P_201704 VALUES LESS THAN (to_timestamp('201705', 'YYYYMM')),
	PARTITION P_201705 VALUES LESS THAN (to_timestamp('201706', 'YYYYMM')),
	PARTITION P_201706 VALUES LESS THAN (to_timestamp('201707', 'YYYYMM')),
	PARTITION P_201707 VALUES LESS THAN (to_timestamp('201708', 'YYYYMM')),
	PARTITION P_201708 VALUES LESS THAN (to_timestamp('201709', 'YYYYMM')),
	PARTITION P_201709 VALUES LESS THAN (to_timestamp('201710', 'YYYYMM')),
	PARTITION P_201710 VALUES LESS THAN (to_timestamp('201711', 'YYYYMM')),
	PARTITION P_201711 VALUES LESS THAN (to_timestamp('201712', 'YYYYMM')));



CREATE UNIQUE INDEX PK_HEALTH_DAILY_TRX_PDM ON HEALTH_DAILY_TRX_PDM
(EQP_ID  ASC,MEASURE_DTTS  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE HEALTH_DAILY_TRX_PDM
	ADD CONSTRAINT  PK_HEALTH_DAILY_TRX_PDM PRIMARY KEY (EQP_ID,MEASURE_DTTS);



CREATE TABLE HEALTH_MODEL_HST_PDM
(
	EQP_ID                NUMBER(10)  NOT NULL ,
	VERSION               NUMBER(10)  NOT NULL ,
	MODEL_PARAMS          CLOB  NULL ,
	MODEL_OBJ             CLOB  NULL ,
	PCA_MODEL_OBJ         CLOB  NULL ,
	START_DTTS            TIMESTAMP  NULL ,
	END_DTTS              TIMESTAMP  NULL ,
	CREATE_TYPE_CD        VARCHAR2(32)  NULL ,
	CREATE_USER_ID        VARCHAR2(128)  NULL ,
	CREATE_DTTS           TIMESTAMP  NULL ,
	DESCRIPTION           VARCHAR2(1024)  NULL ,
	TARGET                FLOAT(23)  NULL ,
	ALARM_SPEC            FLOAT(23)  NULL ,
	WARN_SPEC             FLOAT(23)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_HEALTH_MODEL_HST_PDM ON HEALTH_MODEL_HST_PDM
(EQP_ID  ASC,VERSION  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE HEALTH_MODEL_HST_PDM
	ADD CONSTRAINT  PK_HEALTH_MODEL_HST_PDM PRIMARY KEY (EQP_ID,VERSION);



CREATE TABLE HEALTH_MODEL_PDM
(
	EQP_ID                NUMBER(10)  NOT NULL ,
	MODEL_PARAMS          CLOB  NULL ,
	MODEL_OBJ             CLOB  NULL ,
	PCA_MODEL_OBJ         CLOB  NULL ,
	START_DTTS            TIMESTAMP  NULL ,
	END_DTTS              TIMESTAMP  NULL ,
	CREATE_TYPE_CD        VARCHAR2(32)  NULL ,
	CREATE_USER_ID        VARCHAR2(128)  NULL ,
	CREATE_DTTS           TIMESTAMP  NULL ,
	DESCRIPTION           VARCHAR2(1024)  NULL ,
	TARGET                FLOAT(23)  NULL ,
	ALARM_SPEC            FLOAT(23)  NULL ,
	WARN_SPEC             FLOAT(23)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_HEALTH_MODEL_PDM ON HEALTH_MODEL_PDM
(EQP_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE HEALTH_MODEL_PDM
	ADD CONSTRAINT  PK_HEALTH_MODEL_PDM PRIMARY KEY (EQP_ID);



CREATE TABLE HEALTH_STAT_TRX_PDM
(
	EQP_ID                NUMBER(10)  NOT NULL ,
	MEASURE_DTTS          TIMESTAMP  NOT NULL ,
	SCORE                 FLOAT(23)  NULL ,
	TOTAL_CNT             NUMBER(10)  NULL ,
	ALARM_CNT             NUMBER(10)  NULL ,
	WARN_CNT              NUMBER(10)  NULL ,
	HEALTH_VARIATION      FLOAT(23)  NULL ,
	EXPECTED_ALARM        NUMBER(10)  NULL ,
	CAUSE1                VARCHAR2(4000)  NULL ,
	CAUSE2                VARCHAR2(4000)  NULL ,
	CAUSE3                CLOB  NULL ,
	ALARM                 NUMBER(5)  NULL ,
	WARN                  NUMBER(5)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_HEALTH_STAT_TRX_PDM ON HEALTH_STAT_TRX_PDM
(EQP_ID  ASC,MEASURE_DTTS  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE HEALTH_STAT_TRX_PDM
	ADD CONSTRAINT  PK_HEALTH_STAT_TRX_PDM PRIMARY KEY (EQP_ID,MEASURE_DTTS);



CREATE TABLE MANUAL_RPM_PDM
(
	PARAM_ID              NUMBER(10)  NOT NULL ,
	RPM                   NUMBER(5)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_MANUAL_RPM_PDM ON MANUAL_RPM_PDM
(PARAM_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE MANUAL_RPM_PDM
	ADD CONSTRAINT  PK_MANUAL_RPM_PDM PRIMARY KEY (PARAM_ID);



CREATE TABLE MEASURE_TRX_BIN_PDM
(
	MEASURE_TRX_ID        NUMBER(10)  NOT NULL ,
	BIN_DATA_TYPE_CD      VARCHAR2(32)  NOT NULL ,
	SCALE_FACTOR          FLOAT(23)  NULL ,
	BINARY                BLOB  NULL 
)
	TABLESPACE OWNER_DAT
	LOB (BINARY) STORE AS  ( 
	TABLESPACE OWNER_LOB);



CREATE UNIQUE INDEX PK_MEASURE_TRX_BIN_PDM ON MEASURE_TRX_BIN_PDM
(MEASURE_TRX_ID  ASC,BIN_DATA_TYPE_CD  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE MEASURE_TRX_BIN_PDM
	ADD CONSTRAINT  PK_MEASURE_TRX_BIN_PDM PRIMARY KEY (MEASURE_TRX_ID,BIN_DATA_TYPE_CD);



CREATE TABLE MEASURE_TRX_PDM
(
	MEASURE_TRX_ID        NUMBER(10)  NOT NULL ,
	MEASURE_DTTS          TIMESTAMP  NULL ,
	PARAM_ID              NUMBER(10)  NOT NULL ,
	VALUE                 FLOAT(23)  NULL ,
	RPM                   FLOAT(23)  NULL ,
	END_FREQ              NUMBER(10)  NULL ,
	SPECTRA_LINE          NUMBER(10)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_MEASURE_TRX_PDM ON MEASURE_TRX_PDM
(MEASURE_TRX_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE MEASURE_TRX_PDM
	ADD CONSTRAINT  PK_MEASURE_TRX_PDM PRIMARY KEY (MEASURE_TRX_ID);



CREATE TABLE OVERALL_MINUTE_AVG90_TRX_PDM
(
	PARAM_ID              NUMBER(10)  NOT NULL ,
	READ_DTTS             TIMESTAMP  NOT NULL ,
	VALUE                 FLOAT(23)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_OVERALL_MINUTE_AVG90_TRX_PD ON OVERALL_MINUTE_AVG90_TRX_PDM
(PARAM_ID  ASC,READ_DTTS  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE OVERALL_MINUTE_AVG90_TRX_PDM
	ADD CONSTRAINT  PK_OVERALL_MINUTE_AVG90_TRX_PD PRIMARY KEY (PARAM_ID,READ_DTTS);



CREATE TABLE OVERALL_MINUTE_SUMMARY_TRX_PDM
(
	READ_DTTS             TIMESTAMP  NOT NULL ,
	PARAM_ID              NUMBER(10)  NOT NULL ,
	ALARM                 FLOAT(23)  NULL ,
	WARN                  FLOAT(23)  NULL ,
	AVG_SPEC              FLOAT(23)  NULL ,
	AVG_DAILY             FLOAT(23)  NULL ,
	AVG_WITH_AW           FLOAT(23)  NULL ,
	VARIATION             FLOAT(23)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_OVERALL_MINUTE_SUMMARY_TRX_ ON OVERALL_MINUTE_SUMMARY_TRX_PDM
(READ_DTTS  ASC,PARAM_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE OVERALL_MINUTE_SUMMARY_TRX_PDM
	ADD CONSTRAINT  PK_OVERALL_MINUTE_SUMMARY_TRX_ PRIMARY KEY (READ_DTTS,PARAM_ID);



CREATE TABLE OVERALL_MINUTE_TRX_PDM
(
	PARAM_ID              NUMBER(10)  NOT NULL ,
	READ_DTTS             TIMESTAMP  NOT NULL ,
	VALUE                 FLOAT(23)  NULL ,
	RPM                   FLOAT(23)  NULL ,
	WARN                  FLOAT(23)  NULL ,
   	ALARM                 FLOAT(23)  NULL
)
	TABLESPACE OWNER_DAT
	PARTITION BY RANGE (READ_DTTS)
	(PARTITION P_201601 VALUES LESS THAN (to_timestamp('201602', 'YYYYMM')),
	PARTITION P_201602 VALUES LESS THAN (to_timestamp('201603', 'YYYYMM')),
	PARTITION P_201603 VALUES LESS THAN (to_timestamp('201604', 'YYYYMM')),
	PARTITION P_201604 VALUES LESS THAN (to_timestamp('201605', 'YYYYMM')),
	PARTITION P_201605 VALUES LESS THAN (to_timestamp('201606', 'YYYYMM')),
	PARTITION P_201606 VALUES LESS THAN (to_timestamp('201607', 'YYYYMM')),
	PARTITION P_201607 VALUES LESS THAN (to_timestamp('201608', 'YYYYMM')),
	PARTITION P_201608 VALUES LESS THAN (to_timestamp('201609', 'YYYYMM')),
	PARTITION P_201609 VALUES LESS THAN (to_timestamp('201610', 'YYYYMM')),
	PARTITION P_201610 VALUES LESS THAN (to_timestamp('201611', 'YYYYMM')),
	PARTITION P_201611 VALUES LESS THAN (to_timestamp('201612', 'YYYYMM')),
	PARTITION P_201612 VALUES LESS THAN (to_timestamp('201701', 'YYYYMM')),
	PARTITION P_201701 VALUES LESS THAN (to_timestamp('201702', 'YYYYMM')),
	PARTITION P_201702 VALUES LESS THAN (to_timestamp('201703', 'YYYYMM')),
	PARTITION P_201703 VALUES LESS THAN (to_timestamp('201704', 'YYYYMM')),
	PARTITION P_201704 VALUES LESS THAN (to_timestamp('201705', 'YYYYMM')),
	PARTITION P_201705 VALUES LESS THAN (to_timestamp('201706', 'YYYYMM')),
	PARTITION P_201706 VALUES LESS THAN (to_timestamp('201707', 'YYYYMM')),
	PARTITION P_201707 VALUES LESS THAN (to_timestamp('201708', 'YYYYMM')),
	PARTITION P_201708 VALUES LESS THAN (to_timestamp('201709', 'YYYYMM')),
	PARTITION P_201709 VALUES LESS THAN (to_timestamp('201710', 'YYYYMM')),
	PARTITION P_201710 VALUES LESS THAN (to_timestamp('201711', 'YYYYMM')),
	PARTITION P_201711 VALUES LESS THAN (to_timestamp('201712', 'YYYYMM')));



CREATE UNIQUE INDEX PK_OVERALL_MINUTE_TRX_PDM ON OVERALL_MINUTE_TRX_PDM
(PARAM_ID  ASC,READ_DTTS  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE OVERALL_MINUTE_TRX_PDM
	ADD CONSTRAINT  PK_OVERALL_MINUTE_TRX_PDM PRIMARY KEY (PARAM_ID,READ_DTTS);



CREATE TABLE OVERALL_SPEC_PDM
(
	PARAM_ID              NUMBER(10)  NOT NULL ,
	WARN                  FLOAT(23)  NULL ,
	ALARM                 FLOAT(23)  NULL 
)
	TABLESPACE OWNER_DAT;




CREATE UNIQUE INDEX PK_OVERALL_SPEC_PDM ON OVERALL_SPEC_PDM
(PARAM_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE OVERALL_SPEC_PDM
	ADD CONSTRAINT  PK_OVERALL_SPEC_PDM PRIMARY KEY (PARAM_ID);







CREATE TABLE PARAM_COMMON_PDM
(
	PARAM_ID              NUMBER(10)  NOT NULL ,
	EU                    VARCHAR2(128)  NULL ,
	EU_TYPE               NUMBER(10)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_PARAM_COMMON_PDM ON PARAM_COMMON_PDM
(PARAM_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE PARAM_COMMON_PDM
	ADD CONSTRAINT  PK_PARAM_COMMON_PDM PRIMARY KEY (PARAM_ID);



CREATE TABLE PARAM_PART_LNK_PDM
(
	PARAM_ID              NUMBER(10)  NOT NULL ,
	PART_ID               NUMBER(10)  NOT NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_PARAM_PART_LNK_PDM ON PARAM_PART_LNK_PDM
(PARAM_ID  ASC,PART_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE PARAM_PART_LNK_PDM
	ADD CONSTRAINT  PK_PARAM_PART_LNK_PDM PRIMARY KEY (PARAM_ID,PART_ID);



CREATE TABLE PARAM_PDM
(
	PARAM_ID              NUMBER(10)  NOT NULL ,
	NAME                  VARCHAR2(128)  NULL ,
	PARAM_TYPE            NUMBER(10)  NULL ,
	EQP_ID                NUMBER(10)  NOT NULL ,
	DESCRIPTION           VARCHAR2(1024)  NULL ,
	SORT_ORDER            NUMBER(3)   DEFAULT  0 NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_PARAM_PDM ON PARAM_PDM
(PARAM_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE PARAM_PDM
	ADD CONSTRAINT  PK_PARAM_PDM PRIMARY KEY (PARAM_ID);



CREATE TABLE PART_PDM
(
	PART_ID               NUMBER(10)  NOT NULL ,
	NAME                  VARCHAR2(128)  NULL ,
	RATIO                 NUMBER(10,2)  NULL ,
	NPAR1                 NUMBER(5)  NULL ,
	NPAR2                 VARCHAR2(20)  NULL ,
	SORT_ORDER            NUMBER(3)  NULL ,
	EQP_ID                NUMBER(10)  NOT NULL ,
	PART_TYPE_ID          NUMBER(10)  NOT NULL ,
	SPEED_PARAM_ID        NUMBER(10)  NOT NULL ,
	MODEL_NUMBER          VARCHAR2(128)  NULL ,
	MANUFACTURE           VARCHAR2(128)  NULL
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_PART_PDM ON PART_PDM
(PART_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE PART_PDM
	ADD CONSTRAINT  PK_PART_PDM PRIMARY KEY (PART_ID);



CREATE TABLE PART_TYPE_PDM
(
	PART_TYPE_ID          NUMBER(10)  NOT NULL ,
	NAME                  VARCHAR2(128)  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_PART_TYPE_PDM ON PART_TYPE_PDM
(PART_TYPE_ID  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE PART_TYPE_PDM
	ADD CONSTRAINT  PK_PART_TYPE_PDM PRIMARY KEY (PART_TYPE_ID);



CREATE TABLE REPORT_ALARM_TRX_PDM
(
	EQP_ID                NUMBER(10)  NOT NULL ,
	OCCUR_DTTS            TIMESTAMP  NOT NULL ,
	SCORE                 FLOAT(23)  NULL ,
	STATE_CD              VARCHAR2(32)  NULL ,
	COMPLETE_DTTS         TIMESTAMP  NULL ,
	COMPLETE_USER_ID      VARCHAR2(128)  NULL ,
	WRITE_DTTS            TIMESTAMP  NULL ,
	REQUEST_DTTS          TIMESTAMP  NULL ,
	REQUEST_USER_ID       VARCHAR2(128)  NULL ,
	CAUSE1                VARCHAR2(4000)  NULL ,
	CAUSE2                VARCHAR2(4000)  NULL ,
	CAUSE3                CLOB  NULL ,
	CAUSE_UPDATE          CLOB  NULL ,
	PARAM_ID              NUMBER(10)  NOT NULL ,
	MEASURE_TRX_ID        NUMBER(10)  NOT NULL ,
	CONTENT               CLOB  NULL 
)
	TABLESPACE OWNER_DAT;



CREATE UNIQUE INDEX PK_REPORT_ALARM_TRX_PDM ON REPORT_ALARM_TRX_PDM
(EQP_ID  ASC,OCCUR_DTTS  ASC)
	TABLESPACE OWNER_IDX;



ALTER TABLE REPORT_ALARM_TRX_PDM
	ADD CONSTRAINT  PK_REPORT_ALARM_TRX_PDM PRIMARY KEY (EQP_ID,OCCUR_DTTS);


