/*

    HMP init scritpts

*/

CREATE TABLESPACE MI_DAT DATAFILE 'MI_DAT.DBF' SIZE 1024M  AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
CREATE TABLESPACE MI_IDX DATAFILE 'MI_IDX.DBF' SIZE 1024M  AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CREATE TABLESPACE OWNER_DAT DATAFILE
    '/<db datafile 위치 디렉토리>/OWNER_DAT01.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/OWNER_DAT02.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/OWNER_DAT03.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/OWNER_DAT04.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/OWNER_DAT05.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING PERMANENT;

CREATE TABLESPACE OWNER_IDX DATAFILE
    '/<db datafile 위치 디렉토리>/OWNER_IDX01.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/OWNER_IDX02.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/OWNER_IDX03.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/OWNER_IDX04.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/OWNER_IDX05.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING PERMANENT;

CREATE TABLESPACE OWNER_LOB DATAFILE
    '/<db datafile 위치 디렉토리>/OWNER_LOB01.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/OWNER_LOB02.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/OWNER_LOB03.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/OWNER_LOB04.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED,
    '/<db datafile 위치 디렉토리>/OWNER_LOB05.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING PERMANENT;​

/*
e.g.
-- add data file
ALTER TABLESPACE OWNER_DAT
    ADD DATAFILE '/u02/oracle/rbdb1/users03.dbf' SIZE 10M
      AUTOEXTEND ON
      NEXT 512K
      MAXSIZE 250M;
*/


/*

    User Creation scripts

*/

CREATE USER MI IDENTIFIED BY bistel01 DEFAULT TABLESPACE MI_DAT;
CREATE USER OWNER IDENTIFIED BY bistel01 DEFAULT TABLESPACE OWNER_DAT;

GRANT CONNECT, RESOURCE TO MI, OWNER;

GRANT RESTRICTED SESSION,CREATE SESSION,RESOURCE TO MI;
GRANT RESTRICTED SESSION,CREATE SESSION,RESOURCE,CREATE VIEW TO OWNER;

ALTER USER MI DEFAULT TABLESPACE MI_DAT QUOTA UNLIMITED ON MI_DAT;
ALTER USER MI DEFAULT TABLESPACE MI_IDX QUOTA UNLIMITED ON MI_IDX;

ALTER USER OWNER DEFAULT TABLESPACE OWNER_DAT QUOTA UNLIMITED ON OWNER_DAT;
ALTER USER OWNER DEFAULT TABLESPACE OWNER_IDX QUOTA UNLIMITED ON OWNER_IDX;
ALTER USER OWNER DEFAULT TABLESPACE OWNER_LOB QUOTA UNLIMITED ON OWNER_LOB;

/*
e.g.
create user npdm identified by bistel01 default tablespace npdm_dat;
grant connect, resource to npdm;

*/