INSERT INTO USER_A3 (USER_ID,NAME,PASSWORD) VALUES ('SA','System Admin','MQ==');
INSERT INTO USER_GROUP_A3(USER_GROUP_ID) VALUES ('ADMIN_GROUP');
INSERT INTO USER_GROUP_LNK_A3(USER_ID,USER_GROUP_ID) VALUES ('SA','ADMIN_GROUP');

INSERT INTO WIDGET_TYPE_A3(WIDGET_TYPE_ID,NAME,TITLE,THUMBNAIL,DESCRIPTION,WIDTH,HEIGHT,CATEGORY,PROPERTIES,USED)VALUES(SEQ_WIDGET_TYPE_A3.nextval,'pdmAreaStatusOverview','Shop Status Overview',NULL,'Shop Status Overview Chart',24,5,NULL,NULL,'Y');
INSERT INTO WIDGET_TYPE_A3(WIDGET_TYPE_ID,NAME,TITLE,THUMBNAIL,DESCRIPTION,WIDTH,HEIGHT,CATEGORY,PROPERTIES,USED)VALUES(SEQ_WIDGET_TYPE_A3.nextval,'pdmEqpStatusOverview','EQP Status Overview',NULL,'EQP Status Overview Chart',24,7,NULL,NULL,'Y');
INSERT INTO WIDGET_TYPE_A3(WIDGET_TYPE_ID,NAME,TITLE,THUMBNAIL,DESCRIPTION,WIDTH,HEIGHT,CATEGORY,PROPERTIES,USED)VALUES(SEQ_WIDGET_TYPE_A3.nextval,'pdmEqpParamAnalysis','EQP Param Analysis',NULL,'EQP Param Analysis Chart',24,12,NULL,NULL,'Y');
INSERT INTO WIDGET_TYPE_A3(WIDGET_TYPE_ID,NAME,TITLE,THUMBNAIL,DESCRIPTION,WIDTH,HEIGHT,CATEGORY,PROPERTIES,USED)VALUES(SEQ_WIDGET_TYPE_A3.nextval,'pdmModeler','Modeler Widget',NULL,'Modeler Widget Chart',24,12,NULL,NULL,'Y');
INSERT INTO WIDGET_TYPE_A3(WIDGET_TYPE_ID,NAME,TITLE,THUMBNAIL,DESCRIPTION,WIDTH,HEIGHT,CATEGORY,PROPERTIES,USED)VALUES(SEQ_WIDGET_TYPE_A3.nextval,'pdmModelingStatus','Modeling Status',NULL,'Modeling Status Chart',24,12,NULL,NULL,'Y');
INSERT INTO WIDGET_TYPE_A3(WIDGET_TYPE_ID,NAME,TITLE,THUMBNAIL,DESCRIPTION,WIDTH,HEIGHT,CATEGORY,PROPERTIES,USED)VALUES(SEQ_WIDGET_TYPE_A3.nextval,'pdmReport','Report',NULL,'Report Chart',24,12,NULL,NULL,'Y');
INSERT INTO WIDGET_TYPE_A3(WIDGET_TYPE_ID,NAME,TITLE,THUMBNAIL,DESCRIPTION,WIDTH,HEIGHT,CATEGORY,PROPERTIES,USED)VALUES(SEQ_WIDGET_TYPE_A3.nextval,'pdmCurrentAnalysis','Current Analysis Widget',NULL,'Current Analysis Widget',24,12,NULL,NULL,'Y');

insert into app_a3(app_id, name) values (SEQ_APP_A3.nextval, 'PDM');

INSERT INTO CODE_CATEGORY_A3(CODE_CATEGORY_ID, APP_ID, NAME)VALUES(SEQ_CODE_CATEGORY_A3.nextval, SEQ_APP_A3.currval, 'FAILURE_TYPE');
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '0', '베어링',   'Y', 0, 'Y', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '1', '모터',    'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '2', '풀리/벨트', 'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '3', '윤활',    'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '4', '정렬 불량', 'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '5', '불균형',   'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '6', '헐거움',   'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '7', '기타',    'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);

INSERT INTO CODE_CATEGORY_A3(CODE_CATEGORY_ID, APP_ID, NAME)VALUES(SEQ_CODE_CATEGORY_A3.nextval, SEQ_APP_A3.currval, 'REPORT_STATUS');
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '0', '발생',    'Y', 0, 'Y', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '1', '확인',    'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '2', '조치요청',  'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '3', '조치완료',  'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);

INSERT INTO CODE_CATEGORY_A3(CODE_CATEGORY_ID, APP_ID, NAME)VALUES(SEQ_CODE_CATEGORY_A3.nextval, SEQ_APP_A3.currval, 'ALARM_CODE');
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '256', 'ALARM',    'Y', 0, 'Y', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '128', 'WARNING',    'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '-1', 'INACTIVE',  'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);


INSERT INTO CODE_CATEGORY_A3(CODE_CATEGORY_ID, APP_ID, NAME)VALUES(SEQ_CODE_CATEGORY_A3.nextval, SEQ_APP_A3.currval, 'PARAM_TYPE');
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '1', '가속도',    'Y', 0, 'Y', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '4', '속도',    'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, '7', '엔벨로핑',  'Y', 0, 'N', NULL, SEQ_CODE_CATEGORY_A3.currval);


INSERT INTO CODE_CATEGORY_A3(CODE_CATEGORY_ID, APP_ID, NAME)VALUES(SEQ_CODE_CATEGORY_A3.nextval, SEQ_APP_A3.currval, 'JOB');
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, 'createPartition', 'Create Partition',    'Y', 0, 'Y', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, 'datapumpBase', 'Base Datapump',    'Y', 0, 'Y', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, 'datapump', 'Datapump',    'Y', 0, 'Y', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, 'createdata', 'CreateData',    'Y', 0, 'Y', NULL, SEQ_CODE_CATEGORY_A3.currval);


INSERT INTO CODE_CATEGORY_A3(CODE_CATEGORY_ID, APP_ID, NAME)VALUES(SEQ_CODE_CATEGORY_A3.nextval, SEQ_APP_A3.currval, 'JOB_STATUS');
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, 'start', 'Start',    'Y', 0, 'Y', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, 'done', 'Done',    'Y', 0, 'Y', NULL, SEQ_CODE_CATEGORY_A3.currval);

INSERT INTO CODE_CATEGORY_A3(CODE_CATEGORY_ID, APP_ID, NAME)VALUES(SEQ_CODE_CATEGORY_A3.nextval, SEQ_APP_A3.currval, 'JOB_TYPE');
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, 'SCHEDULER', 'Scheduler',    'Y', 0, 'Y', NULL, SEQ_CODE_CATEGORY_A3.currval);
INSERT INTO CODE_A3(CODE_ID, CODE, NAME, USED, CODE_ORDER, CODE_DEFAULT, DESCRIPTION, CODE_CATEGORY_ID)VALUES(SEQ_CODE_A3.nextval, 'MANUAL', 'Manual',    'Y', 0, 'Y', NULL, SEQ_CODE_CATEGORY_A3.currval);